### PR TITLE
Create Automate the web browser.pl

### PR DESCRIPTION
**Pull request by rai-gaurav**
This is just a small example of automating the Firefox browser.
Reference - https://metacpan.org/pod/Firefox::Marionette

### CODE REVIEW

**Comment by rai-gaurav** [comment]
There are 2 scripts in this pull request.
1. One for automating Firefox browser
2. For creating charts using [Chart::Plotly](https://metacpan.org/pod/Chart::Plotly). Currently it contains simple example for line chart.

**Comment by nicomen** [comment]
Great! Would it make sense to not comment the statements in the Firefox::Marionette example?

**Comment by rai-gaurav** [comment]
Let me remove comment and check it. Will update it based on that.

**Comment by bbrtj** [comment]
Hey, good job, I've been wondering about the firefox snippet. It contains a lot of commented out calls that all do different stuff. I wonder if it can be streamlined a bit. Just a suggestion: maybe just make a screenshot of the loaded page and save it somewhere? This way there would be no need to sleep at the end.

**Comment by nicomen** [comment]
Thanks will merge the commits. I might end up compacting the firefox example if needed though. I hope that's ok?

**Comment by rai-gaurav** [comment]
No issues. I also think it is little big. There is lot of things to say in a small space.
Also, I haven't done with the change. I will create a separate PR for the screenshots of these scripts.

**Comment by nicomen** [comment]
I am not so sure the site is suitable for screenshots at the moment. I think it should rather encourage people to try out the snippets themselves.

**Comment by bbrtj** [comment]
@rai-gaurav Sorry if I created confusion. What I meant is for the script to create and save a screenshot instead of sleeping for 5 seconds - and it is what it does right now, so that's great. I don't think there's a need for screenshots to be uploaded to the repository.

**Comment by rai-gaurav** [comment]
oops, my bad. No issues. I am also not sure where we will be showing those screenshots.
I will close the other pull request.
One thing there is a 'screenshots' dir in 'main' branch which need to be deleted as it will not be used.

**Pull request merged**
